# Generated by Django 4.2.8 on 2024-01-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_cast_movie_cast1_movie_cast2'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='desc',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
